Working GitHub Action: # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - <your web app name here>

env: # Or as an environment variable
      APP_CONFIGURATION_CONNECTION_STRING: ${{ secrets.APP_CONFIGURATION_CONNECTION_STRING }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
   
    - name: Build with Maven
      run: mvn package --s settings.xml
      env: 
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your web app name here>'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8cbbe98132394af1a139a3f9d4ce8345 }}
        package: '${{ github.workspace }}/target/*.jar'
© 2021 GitHub, Inc.
